name: surf_lint_rules
version: 2.0.0
description: Lint rules for "Surf" company for Dart and Flutter projects.
repository: "https://github.com/surfstudio/flutter-surf-lint-rules"
issue_tracker: "https://github.com/surfstudio/flutter-surf-lint-rules/issues"

dependencies:
  dart_code_metrics: ^5.4.0
  flutter_lints: ^2.0.1

environment:
  sdk: ">=2.13.0 <3.0.0"
